Repository Aeri4a/json-tools-io2024, pull requests merged in 2024-12, with the labels that each got.

#55 [T17] Compare Functionality
  pom.xml
  src/main/java/pl/put/poznan/jsontools/JsonToolsController.java
  src/main/java/pl/put/poznan/jsontools/JsonToolsService.java
  src/main/java/pl/put/poznan/jsontools/types/InputCompareDto.java
  src/main/java/pl/put/poznan/jsontools/types/OutputCompareDto.java
Labels: feature

#56 [T19] Stworzenie klasy testującej JsonMapper
  pom.xml
  src/main/java/pl/put/poznan/jsontools/jsonmapper/JsonMapper.java
  src/test/java/pl/put/poznan/jsontools/jsonmapper/JsonMapperTest.java
Labels: testing

#57 [T21] JsonToolService testing class - minify and format methods
  pom.xml
  src/main/java/pl/put/poznan/jsontools/JsonToolsService.java
  src/test/java/pl/put/poznan/jsontools/JsonToolsServiceTest.java
Labels: testing

#59 [T24] Javadoc comments for decorator related classes
  src/main/java/pl/put/poznan/jsontools/JsonToolsService.java
  src/main/java/pl/put/poznan/jsontools/decorators/ExclusionDecorator.java
  src/main/java/pl/put/poznan/jsontools/decorators/InclusionDecorator.java
  src/main/java/pl/put/poznan/jsontools/decorators/JsonDecorator.java
  src/main/java/pl/put/poznan/jsontools/types/JsonDto.java
Labels: documentation, maintance

#61 [T18] Unnesting Functionality
  pom.xml
  src/main/java/pl/put/poznan/jsontools/JsonToolsController.java
  src/main/java/pl/put/poznan/jsontools/JsonToolsService.java
  src/main/java/pl/put/poznan/jsontools/jsonmapper/JsonMapper.java
  src/main/java/pl/put/poznan/jsontools/types/UnnestedJsonDto.java
Labels: feature
